### ISSUE TITLE
[Backend][Logic] Реализовать Decryptor

### ISSUE THREAD

**Issue by alex-ks** [alex-ks/backend-comptech#18]
Реализовать класс, который будет расшифровывать изображение, полученное из мобильного приложения, используя библиотеку команды Security.

**Comment by whyamiroot** [comment]
- [x] Реализовать статический класс с методом Decrypt, который является обёрткой к библиотеке от команды Security
- [x] Импортировать библиотеку и написать вызов функции расшифровки из библиотеки
5edb5eabe40f6854ffd2a33219cb9ab17354b3ef
