### ISSUE TITLE
Зафиксировать требования

### ISSUE THREAD

**Issue by DVEfremov** [alex-ks/backend-comptech#2]
В https://docs.google.com/document/d/1VPT_Vy5G8aYb4o5RP1DE35OUZRnDJdIm2Lkz_H6ftGM/edit#
завификсировать требования и отслеживать измнения API 
постоянно координируя с другими командами  через тимлидов или отвественных лиц

**Comment by lbdlbdlbdl** [comment]
- [ ] Use-case (для front-end и mobile)
- [ ]  Сценарии использования
- [ ]  Диаграмма с REST-интерфейсами
- [ ] Диаграмма классов
