### ISSUE TITLE
API взаимодействия с Android API

### ISSUE THREAD

**Issue by DVEfremov** [alex-ks/backend-comptech#3]
Проработать API взаимодействия с Android API
и реализовать dummy имплементацию

**Comment by whyamiroot** [comment]
## Черновой вариант API взаимодействия с мобильным устройством
1. Мы получаем POST запрос - .../rest/#?login=_login_&pass=_pass_
Мы отвечаем - токен
2. Мы получаем POST запрос - .../rest/#?token=_token_
Фотография типа multipart, не знаю, как это будет выглядеть в запросе
Мы отвечаем - Валидна или не валидна фотография.
3. Мы получаем POST запрос - .../rest#?token=_token_&bpm=_bpm_
Мы отвечаем только статусом 200 OK, если всё хорошо
4. Мы получаем POST запрос - .../rest/#?token=_token_&finished=1
Тренировка завершена. Если всё хорошо, то обычный 200 OK

**Comment by alex-ks** [comment]
Все запросы идут на один адрес. Это как создаёт неоднозначность по методам (не из имён же аргументов выводить метод), так и плохо с точки зрения дизайна - в REST операции должны быть определены над ресурсами. Пример:
```HTTP
POST /rest/bpm
Authorization: Bearer <token> // токен передаётся в http-заголовке

{
   "value":90
}
```
Соответственно, нужно определить ресурсы, над которыми будут выполняться операции.

Ответить, валидна или не валидна фотография, мы сразу не сможем - нам нужно дождаться окончания обработки, и мобильное приложение об этом уже не узнает.

Да, если мы будем использовать .NET, то методы логина будут сгенерированы фреймворком за нас, конкретный путь точно не помню.

**Comment by whyamiroot** [comment]
## Обновлённый API
1. Авторизация
```
Request: POST .../rest/login
{
    "login": "_login_"
    "pass":"_pass_"
}
Response:
{
    "token":"_token_"
}
```
2. Photo
```
POST Request .../rest/photo
Authorization: Bearer <token> // токен в http-заголовке
{
    "image":"_image_" // Зашифрованная картинка в виде base64
    "timestamp":"_tiestamp_" // Дата время
}
Response:
{
    "message":"OK" // всё ок
              "Err" // произошла какая-то ошибка
}
```
3. Получение пульса
```
POST Request .../rest/bpm
Authorization: Bearer <token> // токен в http-заголовке
{
    "bpm":_bpm_
}
Response:
{
    "message":"OK" // всё ок
              "Err" // какая-то ошибка
}
```
4. Тренировка закончена
```
POST Request .../rest/finished
Authorization: Bearer <token> // токен в http-заголовке
{
    "finished": 1
}
Response:
{
    "message":"OK" // всё ок
              "Err" // какая-то ошибка
}
```

**Comment by alex-ks** [comment]
Думаю, что для пунктов 2-4 вполне достаточно возвращать 200 OK или 40X Error Code без тела ответа.

**Comment by whyamiroot** [comment]
Я думаю, что следует учесть, что фронт к нам тоже по REST ходить будет и сделать запросы вида "...rest/mobile/login" и так далее

**Comment by alex-ks** [comment]
Не имеет смысла дробить API на mobile и frontend - во-первых, так мы привязываемся к конкретным сервисам, во-вторых, механизмы взаимодействия (и ресурсы) будут одними и теми же.

**Comment by ToxikCoder** [comment]
## Финальный вариант

**Comment by whyamiroot** [comment]
## Финальный вариант
1. Авторизация
```
POST Request .../rest/token
{
    "userName": "...",
    "password":"...",
}
Response:
{
    "token":"_token_"
}
```
2. Photo
```
POST Request .../rest/photo
Authorization: Bearer <token> // токен в http-заголовке
{
    "image":"_image_", // Зашифрованная картинка в виде base64
    "timestamp":"_tiestamp_" // Дата время
}
Response: HTTP Status codes
```
3. Получение пульса
```
POST Request .../rest/bpm
Authorization: Bearer <token> // токен в http-заголовке
{
    "bpm":"_bpm_" // зашифрованный пульс
}
Response: HTTP Status codes
```
4. Тренировка закончена
```
POST Request .../rest/finished
Authorization: Bearer <token> // токен в http-заголовке
{
    "finished": 1
}
Response: HTTP Status codes
```

**Comment by alex-ks** [comment]
[Ссылка на API](https://github.com/Onotole1/MobileWinterSchool/wiki/%D0%9E%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5-Service-Api)
