### ISSUE TITLE
API взаимодействия с NeuroNet Service

### ISSUE THREAD

**Issue by DVEfremov** [alex-ks/backend-comptech#4]

**Comment by ky-lian** [comment]
REST сервис NeuroNet должен предоставлять интерфейс:
GET запрос для постановки фотографии в очередь. Отправляем фотографию в Base64. Ожидаем результат в виде значений координат двух точек и угла наклона.

**Comment by alex-ks** [comment]
[Описание API](https://github.com/alex-ks/backend-comptech/wiki/%D0%9E%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5-Service-API)
