### ISSUE TITLE
API взаимодействия с DB (DAO level)

### ISSUE THREAD

**Issue by DVEfremov** [alex-ks/backend-comptech#5]

**Comment by amakalev** [comment]
![img_20170201_214410_hdr](https://cloud.githubusercontent.com/assets/22714879/22512797/bd4ffa5a-e8cc-11e6-966f-c05028f2b130.jpg)

**Comment by lbdlbdlbdl** [comment]
![dal](https://cloud.githubusercontent.com/assets/17801387/22536936/2d0199a4-e917-11e6-8396-1ef2e2f31b88.png)

**Comment by lbdlbdlbdl** [comment]
![dal ](https://cloud.githubusercontent.com/assets/17801387/22536951/596851d6-e917-11e6-90b7-e8ff42ce5ce4.png)

**Comment by lbdlbdlbdl** [comment]
![dal](https://cloud.githubusercontent.com/assets/17801387/22537186/511fb51c-e919-11e6-95c2-3392a0d4c3a6.png)

**Comment by lbdlbdlbdl** [comment]
![uml](https://cloud.githubusercontent.com/assets/17801387/22562411/fda40032-e9ae-11e6-8279-9b9ef9a7fda9.png)

**Comment by lbdlbdlbdl** [comment]
![image](https://cloud.githubusercontent.com/assets/17801387/22562456/2bf22888-e9af-11e6-824c-72718764ae37.png)

**Comment by lbdlbdlbdl** [comment]
- void Add(T entity);
- void Update(T entity);

- GetLastPulseForUser(int userId);
- GetLastPhotoIdForUser(int userId);
- GetRecognitionResultsByPhotoId();

- GetNeuroNetModelId(string str);
- GetCascadeModelId(string str);

Для аналитики:
- GetPhotoById(int id);

**Comment by alex-ks** [comment]
[Описание API](https://github.com/alex-ks/backend-comptech/wiki/%D0%9E%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5-Service-API)
