### ISSUE TITLE
API взаимодействия с Frontend

### ISSUE THREAD

**Issue by alex-ks** [alex-ks/backend-comptech#6]

**Comment by Burize** [comment]
1) POST   /rest/registration
REQUSET json{ login:"", password:""}
RESPONSE 200 при удачной регистрации и 409 при неудаче (уже занятом логине)

2) POST  rest/login
REQUSET json{ login:"", password:""}
RESPONSE json {token:""} or 409 при неверном пароле/406 при неверном логине/пароле
//не уверен что нужно использовать именно такие коды ...
3)POST  /rest/face  
REQUEST json{id:"", token:""}
RESPONSE json{ foto: "" , cordinates: "" (пока не обсуждали будет ли это отдельные 2 переменные по x и y, или же структура), angle: "" }

4)GET.  rest/pulse
REQUSET {id:"", token:""}
RESPONSE {pulse: , state: {"yes","no"}} 
503 при прерывания соединения в БД.
//state - состояние тренировки.
5)POST /rest/logout
REQUEST json{ token: ""}
RESPONSE 200;

**Comment by alex-ks** [comment]
Почему в п.3 POST? Разве этот запрос меняет состояние сервиса?

**Comment by Burize** [comment]
### Изменено

1) POST   /rest/registration
REQUSET json{ login:"", pass:""}
RESPONSE 200 при удачной регистрации и 409 при неудаче (уже занятом логине)

2) POST  rest/login
REQUSET json{ login:"", pass:""}
RESPONSE json {token:""} or 409 при неверном логине/пароле

3) GET  /rest/face  
REQUEST json{ token:""}
RESPONSE json{ valid: {valid, invalid, process},foto: "" , cordinates: { X1:"", Y1:"",  X2:"", Y2:""}, angle: "" } 

4) GET.  rest/pulse
REQUSET {token:""}
RESPONSE {pulse: , state: {"yes","no"}}, при state == no, pulse==null.
503 при прерывания соединения в БД.
//state - состояние тренировки.

5) DELETE /rest/logout
REQUEST json{ token: ""}
RESPONSE 200;

**Comment by alex-ks** [comment]
[Ссылка на API](https://github.com/allyna-mozhina/frontend-comptech/wiki/%D0%9E%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5-Service-API)
