### ISSUE TITLE
[Backend][Controllers] Приём фото с мобильного приложения

### ISSUE THREAD

**Issue by alex-ks** [alex-ks/backend-comptech#8]
Реализовать приём фотографии от мобильного приложения и постановку в очередь на исполнение

**Comment by lbdlbdlbdl** [comment]
```
POST http://host:port/rest/photo
Content-Type: application/json
Authorization: Bearer <token>
```
Запрос:

```
{
    "image" : "_image_",
    "timestamp" : "_timestamp_"
}
```
Ответ: ID сессии

Начать тренировку:
- приложение посылает запрос о начале тренировки с фотографией в зашифрованном виде и временем;
- система делает запрос к БД о последней сессии;
- если состояние запрошенной сессии “в прогрессе”, система шлет ответ мобильному приложению о невозможности начать сессию;
- если состояние запрошенной сессии “завершено”, система создает новую сессию, задает ей Id и значение состояния сессии изменяется на “в прогрессе”, объект сессии посылается в базу данных;
- система расшифровывает фотографию и кладет ее в базу данных;
- система посылает Id сессии мобильному приложению.

Далее отправляем фото на аналитику.

Отправить фото:
- система расшифровывает фотографию и кладет ее в базу данных;
- Id фотографии и Id модели отправляется в очередь на обработку на сервер аналитики, сервер аналитики возвращает GuId процесса;
- когда очередь на отправку фото дошла, делаем запрос по Id фото в бд и отправляем эту фотографию;
- после того, как фото отправили на сервер аналитики, система раз в какой-либо, заранее установленный, промежуток времени опрашивает сервер аналитики о завершении процесса обработки фотографии;
- получаем ответ от сервера аналитики;
- данные о  распознавании фотографии отправляем в базу данных;

**Comment by lbdlbdlbdl** [comment]
- [x] Изменить SessionTracker в зависимости от DomainEntites
- [x] to Startup.cs настроить DI-контейнер, связать с timeout'ом из appsettings.json

**Comment by lbdlbdlbdl** [comment]
- [ ] SessionAccessot.GetSession
- [ ] SessionFilter.InActionExecuting

**Comment by lbdlbdlbdl** [comment]
61077e07c5dce554964a269cf51bc6aeec94a7cf Implemented: SessionTracker for starting and ending session; added UploadPhotoAndStartSession method which gets request from mobile app, create new session and returns sessionId.
